version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: docker-node-tut
    restart: always
    ports:
    -4026:8080
    command: bash -c /usrsrc/app/start.sh

docker compose up

380af1cc9b0112dab0d8d7e6088a8d8fd5ebf59ad71f6d26ac8de0608d7bea49 172.17.0.2
